entryTypes:
  - id: _ET_CONCEPT
    name: Concept
    description: An OpenAlex Concept
    friendlyIdPrefix: C
    enabledFeatures: {}
  - id: _ET_INSTITUTION
    name: Institution
    description: An OpenAlex Institution
    friendlyIdPrefix: I
    enabledFeatures: {}
  - id: _ET_AUTHOR
    name: Author
    description: An OpenAlex Author
    friendlyIdPrefix: A
    enabledFeatures: {}
  - id: _ET_VENUE
    name: Venue
    description: An OpenAlex Venue
    friendlyIdPrefix: V
    enabledFeatures: {}
properties:

#  NON-RELATIONSHIPS
  - id: _PROP_WIKIDATA
    name: Wikidata
    descriptionMD: The Wikidata ID for this concept. 
    type: VALUE
    mode: REC
    rank: 3
    appliesTo:
      - entryType: _ET_CONCEPT
      - entryType: _ET_INSTITUTION
    displayAs: "[{value}](https://www.wikidata.org/wiki/{value})"
  - id: _PROP_LEVEL
    name: Level
    descriptionMD: The level in the concept tree where this concept lives.
    type: VALUE
    mode: REC
    rank: 2
    appliesTo:
      - entryType: _ET_CONCEPT
  - id: _PROP_WORKS_COUNT
    name: Works Count
    descriptionMD: The number of works tagged with this concept.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryType: _ET_CONCEPT
      - entryType: _ET_INSTITUTION
      - entryType: _ET_AUTHOR
      - entryType: _ET_VENUE
  - id: _CITED_BY_COUNT
    name: Cited By Count
    descriptionMD: The number of citations accumulated.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_AUTHOR
      - entryType: _ET_VENUE
      - entryType: _ET_WORK
  - id: _PROP_MAG_ID
    name: MAG ID
    descriptionMD: Microsoft Academic Graph ID.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryType: _ET_INSTITUTION
      - entryType: _ET_CONCEPT
      - entryType: _ET_AUTHOR
      - entryType: _ET_VENUE
      - entryType: _ET_WORK
  - id: _PROP_WIKIPEDIA_ID
    name: Wikipedia ID
    descriptionMD: The concept's Wikipedia page URL.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryType: _ET_INSTITUTION
      - entryType: _ET_CONCEPT
      - entryType: _ET_AUTHOR
    displayAs: "[{value}](https://en.wikipedia.org/wiki/{value})"
  - id: _PROP_SCOPUS_ID
    name: SCOPUS ID
    descriptionMD: The concept's SCOPUS page URL.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_AUTHOR
  - id: _PROP_UPDATED_DATE
    name: Updated date
    descriptionMD: The last time anything in this concept object changed, expressed as an ISO 8601 date string. This date is updated for any change at all, including increases in various counts.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryType: _ET_INSTITUTION
      - entryType: _ET_CONCEPT
      - entryType: _ET_AUTHOR
      - entryType: _ET_VENUE
      - entryType: _ET_WORK
  - id: _PROP_ORCID
    name: ORCID
    descriptionMD: The ORCID of the author.
    type: VALUE
    mode: REC
    importance: 2
    appliesTo:
      - entryType: _ET_AUTHOR
  - id: _PROP_ROR
    name: ROR ID
    descriptionMD: Research Organization Registry identifier
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_INSTITUTION
  - id: _PROP_COUNTRY_CODE
    name: Country code
    descriptionMD: Country code
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_INSTITUTION
  - id: _PROP_INSTITUTION_TYPE
    name: Institution type
    descriptionMD: Institution type of eight used to characterize institutions by OpenAlex
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_INSTITUTION
    - id: _PROP_ISSN_L
    name: ISSN-L
    descriptionMD: The ISSN-L or Linking ISSN is a single canonical ISSN for all media versions of the title.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_VENUE
    - id: _PROP_ISSN
    name: ISSN
    descriptionMD: The list of ISSNs for this venue.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_VENUE
    - id: _PROP_COUNTS_BY_YEAR
    name: Counts by year
    descriptionMD: List of works_count and cited_by_count for each of the last ten years, binned by year.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_VENUE
    - id: _PROP_WORKS_API_URL
    name: Works api URL
    descriptionMD: LA URL that will get you a list of all this venue's Works.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_VENUE
    - id: _PROP_DOI
    name: doi
    descriptionMD: Work's doi identifier.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_WORK
    - id: _PROP_TITLE
    name: Title
    descriptionMD: Work's title.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_WORK
    - id: _PROP_PUBLICATION_YEAR
    name: Publication year.
    descriptionMD: Publication year
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_WORK
    - id: _PROP_PUBLICATION_DATE
    name: Publication date
    descriptionMD: Publication date.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_WORK
    - id: _PROP_PMID
    name: PMID
    descriptionMD: Pubmed identifier.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_WORK
    - id: _PROP_PMCID
    name: PMCID
    descriptionMD: Pubmed Central Identifier.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_WORK
    - id: _PROP_IS_OA
    name: Is open-access?
    descriptionMD: Indicates whether the work is open-access.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_WORK
    - id: _PROP_OA_STATUS
    name: Status of open-access.
    descriptionMD: Open-access status. One of "gold", "green", "hybrid", "bronze" and "closed".
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_WORK
    - id: _PROP_OA_URL
    name: Open-access URL.
    descriptionMD: URL to closest to open-access version of a work.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_WORK
    - id: _PROP_IS_RETRACTED
    name: Is the work retracted?
    descriptionMD: Indicates whether the work is retracted.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_WORK
    - id: _PROP_IS_PARATEXT
    name: Is it paratext?
    descriptionMD: Indicates whether the work is a paratext.
    type: VALUE
    mode: REC
    importance: 5
    appliesTo:
      - entryType: _ET_WORK

# RELATIONSHIPS
  - id: _PROP_PARENT_CONCEPT
    name: Parent Concept
    descriptionMD: List of concepts that this concept descends from.
    type: IS_A
    mode: REC
    rank: 0
    appliesTo:
      - entryType: _ET_CONCEPT
    valueConstraint: x.entryType() = entryType("_ET_CONCEPT")
  - id: _PROP_CHILD_CONCEPTS
    name: Child Concepts
    descriptionMD: List of concepts that this concept is a parent of.
    type: RELATES_TO
    mode: AUTO
    rank: 0
    appliesTo:
      - entryType: _ET_CONCEPT
    valueConstraint: x.entryType() = entryType("_ET_CONCEPT")
    default: 'this.reverse(prop=prop("_PROP_PARENT_CONCEPT"))'
    
  - id: _PROP_RELATED_CONCEPTS
    name: Related concepts
    descriptionMD: Concepts that are similar to this one.
    type: RELATES_TO
    mode: REC
    rank: 1
    appliesTo:
      - entryType: _ET_CONCEPT
    valueConstraint: x.entryType() = entryType("_ET_CONCEPT")
  - id: _PROP_PARENT_INSTITUTIONS
    name: Parents
    descriptionMD: List of parent institutions.
    type: RELATES_TO
    mode: REC
    importance: 0
    appliesTo:
      - entryType: _ET_INSTITUTION
    valueConstraint: x.entryType() = entryType("_ET_INSTITUTION")
  - id: _PROP_CHILD_INSTITUTIONS
    name: Child institutions
    descriptionMD: List of child institutions.
    type: RELATES_TO
    mode: AUTO
    importance: 0
    appliesTo:
      - entryType: _ET_INSTITUTION
    valueConstraint: x.entryType() = entryType("_ET_INSTITUTION")
    default: 'this.reverse(prop=[[/prop/_PROP_ANCESTORS]])'
  - id: _PROP_RELATED_INSTITUTIONS
    name: Related institutions
    descriptionMD: List of related institutions.
    type: RELATES_TO
    mode: REC
    importance: 0
    appliesTo:
      - entryType: _ET_INSTITUTION
    valueConstraint: x.entryType() = entryType("_ET_INSTITUTION")
  - id: _PROP_LAST_KNOWN_INSTITUTION
    name: Last known institution
    descriptionMD: Last known associated instituion.
    type: RELATES_TO
    mode: REC
    importance: 0
    appliesTo:
      - entryType: _ET_AUTHOR
    valueConstraint: x.entryType() = entryType("_ET_INSTITUTION")
  - id: _PROP_ASSOCIATED_AUTHOR
    name: Associated author
    descriptionMD: Author associated with this institution.
    type: RELATES_TO
    mode: AUTO
    importance: 0
    appliesTo:
      - entryType: _ET_INSTITUTION
    valueConstraint: x.entryType() = entryType("_ET_AUTHOR")
    default: 'this.reverse(prop=[[/prop/_PROP_LAST_KNOWN_INSTITUTION]])'
  - id: _PROP_HOST_VENUE
    name: Host venue
    descriptionMD: A HostVenue object describing how and where this work is being hosted online.
    type: RELATES_TO
    mode: REC
    importance: 0
    appliesTo:
      - entryType: _ET_WORK
    valueConstraint: x.entryType() = entryType("_ET_VENUE")
  

idMap:
  comment: >-
    if you edit one of the IDs above, you should edit it below here too. You do
    not need to add IDs here for new entries.
  map:
    _ET_CONCEPT: _vj4bFX3CVAGMis4aiL4AJ
    _ET_INSTITUTION: _6IBiJrvrPmEDXVCpdphja2
    _PROP_WIKIDATA: _63mbf1PWCiYQVs53ef3lcp
    _PROP_LEVEL: _3AyM6hRQL23PhhHZrboCYr
    _PROP_WORKS_COUNT: _4OujpOZawdTunrjtSQrPcb
    _PROP_MAG_ID: _1i2GXNofq5YEgaA3R9F4KN
    _PROP_WIKIPEDIA_ID: _468JDObMgV93qhEfHSAWnr
    _PROP_UPDATED_DATE: _1M7JXgQKUfgSageiKdR82T
    _PROP_PARENT_CONCEPT: _1uwLIPU2RI457BkrPs3rgM
    _PROP_RELATED_CONCEPTS: _4wv8wdeT0B33FTQPBcAszM
    _PROP_DESCENDANTS: _5bqPhtxKnanIkfrOUuxq4M
    _PROP_PARENT_INSTITUTIONS: _2WcngIq4qAP8jYL0W1o7iK
    _PROP_CHILD_INSTITUTIONS: _47ihemw9K882NvnTGklODY
    _PROP_RELATED_INSTITUTIONS: _2tGs933dsiNrejnlX8C1cS
    _PROP_SCOPUS_ID: _67iX5qqVN01rUqWk85wzco
    _ET_AUTHOR: _4dQI9bcpJaIbeg2GHgdPgf
    _PROP_ORCID: _7A5Wa42OstkFT0J5uSgQe7
    _CITED_BY_COUNT: _5jsjdLPAL9UK0i3WAQTWXK
    _PROP_LAST_KNOWN_INSTITUTION: _1JFqXKkYV2vYEjiHI1AS2F
    _PROP_ASSOCIATED_AUTHOR: _5l1iUSabWX3Oqglokv1JTZ
    _PROP_ROR: _40f9pqAoVezJMsluDEoX8R
    _PROP_COUNTRY_CODE: _1KL8Jd79CEYP4D0W2ae9jc
    _PROP_INSTITUTION_TYPE: _4ri7I2Si8KbBzj6Ao36cLH
    _ET_VENUE: _5X3C4f0mDy9RKziLpP1Few
    _PROP_ISSN_L: _6iPoU1dsJEyMK6Ui23FtC3
    _PROP_ISSN: _6y3Gun1pkTNoe2F4mQ34i7
    _PROP_COUNTS_BY_YEAR: _iuTgSAnr6HWgJcPGUt7FT
    _PROP_WORKS_API_URL: _2lcWYtipXp6wruM1Euu0GT
    _PROP_DOI: _3W6WCrZ6Q5gfWZI4oHdHOQ
    _PROP_TITLE: _4jbPlGqe23uxRfDoWLH7MI
    _PROP_PUBLICATION_YEAR: _2BGNyG50drPYgjTLIrEaSF
    _PROP_PUBLICATION_DATE: _1VB9bSjlIEcscflCZW5HhL
    _PROP_PMID: _1PGQimSDXfHUcWSiNTU2h0
    _PROP_PMCID: _6wAsbN1UGoBs0ImFU9GJAJ
    _PROP_IS_OA: _2OidkpKVLC8W5B3xjvJaH4
    _PROP_OA_STATUS: _2SHHV1zaxkLuZDipZWsPqy
    _PROP_OA_URL: _6nEVzwO5Dk5LfccIdecfy6
    _PROP_IS_RETRACTED: _2cGjybttDOgsmm6kUe5rqx
    _PROP_IS_PARATEXT: _13TQUi0GMmUCxX1HEdGuF8
    
    
    _PROP_CHILD_CONCEPTS: _5bqPhtxKnanIkfrOUuxq4M
