entryTypes:
  - key: concept
    name: Concept
    description: Topics used to organize works
    keyPrefix: C
    color: emerald
    abbreviation: C
    enabledFeatures: {}
  - key: institution
    name: Institution
    description: A university or other organization that is affiliated with works (via authors)
    keyPrefix: I
    color: blue
    abbreviation: I
    enabledFeatures: {}
  - key: author
    name: Author
    description: A person who creates works
    keyPrefix: A
    color: yellow
    abbreviation: A
    enabledFeatures: {}
  - key: venue
    name: Venue
    description: A journal or repository that hosts works
    keyPrefix: V
    color: red
    abbreviation: V
    enabledFeatures: {}
  - key: host-venue
    name: Host Venue
    description: A journal or repository that hosts a particular work
    keyPrefix: V
    color: red
    abbreviation: V
    enabledFeatures: {}
  - key: work
    name: Work
    description: A scholarly work (papers, books, datasets, etc.)
    keyPrefix: W
    color: ""
    abbreviation: W
    enabledFeatures: {}
properties:
#  NON-RELATIONSHIPS
  - key: url
    name: URL
    description: URL
    type: VALUE
    mode: OPT
    appliesTo:
      - entryTypeKey: host-venue
  - key: openalex-id
    name: OpenAlex ID
    description: The Unique permanent ID for this entity assigned by OpenAlex.
    type: VALUE
    mode: AUTO
    rank: 1
    appliesTo:
      - entryTypeKey: author
      - entryTypeKey: concept
      - entryTypeKey: institution
      - entryTypeKey: venue
      - entryTypeKey: work
    default: this.key
    displayAs: "[{value}](https://openalex.org/{value})"
  - key: wikidata-id
    name: Wikidata
    description: The Wikidata ID for this concept. 
    type: VALUE
    mode: REC
    rank: 3
    appliesTo:
      - entryTypeKey: concept
      - entryTypeKey: institution
      - entryTypeKey: venue
    displayAs: "[{value}](https://www.wikidata.org/wiki/{value})"
  - key: level
    name: Level
    description: The level in the concept tree where this concept lives.
    type: VALUE
    mode: REC
    rank: 2
    appliesTo:
      - entryTypeKey: concept
  - key: works-count
    name: Works Count
    description: The number of works tagged with this entity.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: concept
      - entryTypeKey: institution
      - entryTypeKey: author
      - entryTypeKey: venue
  - key: cited-by-count
    name: Cited By Count
    description: The number of citations accumulated.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: author
      - entryTypeKey: venue
      - entryTypeKey: work
  - key: mag-id
    name: MAG ID
    description: Microsoft Academic Graph ID.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: institution
      - entryTypeKey: concept
      - entryTypeKey: author
      - entryTypeKey: venue
      - entryTypeKey: work
    displayAs: "{value}"  # Display as a string with no commas in it
  - key: wikipedia-id
    name: Wikipedia ID
    description: The concept's Wikipedia page URL.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: institution
      - entryTypeKey: concept
      - entryTypeKey: author
    displayAs: "[{value}](https://en.wikipedia.org/wiki/{value})"
  - key: scopus-id
    name: SCOPUS ID
    description: The author's SCOPUS ID.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: author
    displayAs: "[{value}](http://www.scopus.com/inward/authorDetails.url?authorID={value}&partnerID=MN8TOARS)"
  - key: twitter-handle
    name: Twitter handle
    description: The author's twitter handle
    type: VALUE
    mode: REC
    rank: 10
    appliesTo:
      - entryTypeKey: author
    displayAs: "[@{value}](https://twitter.com/{value})"
  - key: updated-date
    name: Updated date
    description: The last time anything in this entity changed. This date is updated for any change at all, including increases in various counts.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: institution
      - entryTypeKey: concept
      - entryTypeKey: author
      - entryTypeKey: venue
      - entryTypeKey: work
  - key: orcid
    name: ORCID
    description: The ORCID of the author.
    type: VALUE
    mode: REC
    rank: 2
    appliesTo:
      - entryTypeKey: author
  - key: fatcat-id
    name: Fatcat ID
    description: ID of this venue in Fatcat, "a versioned, user-editable catalog of research publications including journal articles, conference proceedings, and datasets."
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: venue
    displayAs: "[{value}](https://fatcat.wiki/container/{value})"
  - key: ror-id
    name: ROR ID
    description: Research Organization Registry identifier
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: institution
    displayAs: "[{value}](https://ror.org/{value})"
  - key: country-code
    name: Country code
    description: Country code
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: institution
  - key: institution-type
    name: Institution type
    description: Institution type of eight used to characterize institutions by OpenAlex
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: institution
  - key: issn-l
    name: ISSN-L
    description: The ISSN-L or Linking ISSN is a single canonical ISSN for all media versions of the title.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: venue
  - key: issn
    name: ISSN
    description: The list of ISSNs for this venue.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: venue
  # - key: counts-by-year
  #   name: Counts by year
  #   description: List of works_count and cited_by_count for each of the last ten years, binned by year.
  #   type: VALUE
  #   mode: REC
  #   rank: 5
  #   appliesTo:
  #     - entryTypeKey: venue
  - key: works-api-url
    name: Works API URL
    description: The URL that will get you a list of all this venue's Works.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: venue
    displayAs: "[{value}]({value})"
  - key: abbreviated-title
    name: Abbreviated Title
    description: An abbreviated title obtained from the [ISSN Centre](https://issn.org/).
    type: VALUE
    mode: REC
    rank: 3
    appliesTo:
      - entryTypeKey: venue
  - key: alternate-titles
    name: Alternate Titles
    description: Alternate titles for this Venue.
    type: VALUE
    mode: REC
    rank: 4
    appliesTo:
      - entryTypeKey: venue
  - key: homepage-url
    name: Homepage URL
    description: The official URL for this institution/venue.
    type: VALUE
    mode: REC
    rank: 6
    appliesTo:
      - entryTypeKey: institution
      - entryTypeKey: venue
  - key: doi
    name: doi
    description: Work's doi identifier.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: work
  - key: title
    name: Title
    description: Work's title.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: work
  - key: publication-year
    name: Publication year.
    description: Publication year
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: work
  - key: publication-date
    name: Publication date
    description: Publication date.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: work
  - key: pmid
    name: PMID
    description: Pubmed identifier.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: work
  - key: pmc-id
    name: PMCID
    description: Pubmed Central Identifier.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: work
  - key: is-open-access
    name: Is open-access?
    description: Indicates whether the work is open-access.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: work
  - key: oa-status
    name: Status of open-access.
    description: Open-access status. One of "gold", "green", "hybrid", "bronze" and "closed".
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: work
  - key: oa-url
    name: Open-access URL.
    description: URL to closest to open-access version of a work.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: work
  - key: is-retracted
    name: Is the work retracted?
    description: Indicates whether the work is retracted.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: work
  - key: is-paratext
    name: Is it paratext?
    description: Indicates whether the work is a paratext.
    type: VALUE
    mode: REC
    rank: 5
    appliesTo:
      - entryTypeKey: work

# RELATIONSHIPS
  - key: parent-concept
    name: Parent Concept
    description: List of concepts that this concept descends from.
    type: IS_A
    mode: REC
    rank: 0
    appliesTo:
      - entryTypeKey: concept
    valueConstraint: x.entryType() = entryType("concept")
  - key: child-concepts
    name: Child Concepts
    description: List of concepts that this concept is a parent of.
    type: RELATES_TO
    mode: AUTO
    rank: 0
    appliesTo:
      - entryTypeKey: concept
    valueConstraint: x.entryType() = entryType("concept")
    default: 'this.reverse(prop=prop("parent-concept"))'
    
  - key: related-concepts
    name: Related concepts
    description: Concepts that are similar to this one.
    type: RELATES_TO
    mode: REC
    rank: 1
    appliesTo:
      - entryTypeKey: concept
    valueConstraint: x.entryType() = entryType("concept")
  - key: parent-institutions
    name: Parents
    description: List of parent institutions.
    type: RELATES_TO
    mode: REC
    rank: 0
    appliesTo:
      - entryTypeKey: institution
    valueConstraint: x.entryType() = entryType("institution")
  - key: child-institutions
    name: Child institutions
    description: List of child institutions.
    type: RELATES_TO
    mode: AUTO
    rank: 0
    appliesTo:
      - entryTypeKey: institution
    valueConstraint: x.entryType() = entryType("institution")
    default: 'this.reverse(prop=prop("parent-institutions"))'
  - key: related-institutions
    name: Related institutions
    description: List of related institutions.
    type: RELATES_TO
    mode: REC
    rank: 0
    appliesTo:
      - entryTypeKey: institution
    valueConstraint: x.entryType() = entryType("institution")
  - key: display-name-alternatives
    name: Also displayed as
    description: Other ways that we've found this author's name displayed.
    type: VALUE
    mode: REC
    rank: 10
    appliesTo:
      - entryTypeKey: author
  - key: last-known-institution
    name: Last known institution
    description: Last known associated instituion.
    type: RELATES_TO
    mode: REC
    rank: 0
    appliesTo:
      - entryTypeKey: author
    valueConstraint: x.entryType() = entryType("institution")
  - key: associated-authors
    name: Associated authors
    description: Authors associated with this institution.
    type: RELATES_TO
    mode: AUTO
    rank: 0
    appliesTo:
      - entryTypeKey: institution
    valueConstraint: x.entryType() = entryType("author")
    default: 'this.reverse(prop=prop("last-known-institution"))'
  - key: has-host-venue
    name: Host venue
    description: A HostVenue object describing how and where this work is being hosted online.
    type: RELATES_TO
    mode: REC
    rank: 0
    appliesTo:
      - entryTypeKey: work
    valueConstraint: x.entryType() = entryType("host-venue")
